DROP DATABASE IF EXISTS business_db;
CREATE DATABASE business_db;

USE business_db;

CREATE TABLE departments (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, -- DEPARTMENT ID
    department_name VARCHAR(30) -- DEPARTMENT NAME
);

CREATE TABLE roles (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, -- ROLE ID
    title VARCHAR(30), -- ROLE TITLE
    salary DECIMAL NOT NULL, -- ROLE SALARY
    department_id INT,
    FOREIGN KEY (department_id) -- REFERENCE TO THE DEPARTMENT THE ROLE BELONGS TO
    REFERENCES departments(id)
    ON DELETE SET NULL -- WHEN THE DEPARTMENT THE ROLE BELONGS TO IS DELETED, SO IS THE ROLE
);

CREATE TABLE employees (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, -- EMPLOYEE ID
    first_name VARCHAR(30), -- EMPLOYEE FIRST NAME
    last_name VARCHAR(30), -- EMPLOYEE LAST NAME
    role_id INT,
    manager_id INT,
    FOREIGN KEY (role_id) -- REFERENCE TO THE EMPLOYEE'S ROLE 
    REFERENCES roles(id)
    ON DELETE SET NULL, -- IF THE EMPLOYEE'S ROLE IS DELETED, SO IS THE EMPLOYEE
    FOREIGN KEY (manager_id)
    REFERENCES employees(id)-- REFERENCE TO ANOTHER EMPLOYEE THAT IS THE MANAGER OF THE CURRENT EMPLOYEE (NULL IF THE EMPLOYEE HAS SO MANAGER)
);